export const MAIN_HEADERS = [
  'Title',
  'Author',
  'Series',
  'Platform',
  'Status',
  'Read?',
  'Liked',
  'Year Finished',
  'Opinion',
  'Notes',
  'Cover URL',
  'Next Rank',
  'Why Next',
  'Pros',
  'Cons',
  'Next Slot',
  'Community Rating',
  'Ratings Count',
  'Rating Source',
  'Rating Updated',
  'Personal Relevance',
  'Relevance Reason',
  'Relevance Updated',
  'Book ID',
  'Updated At',
  'Updated By',
  'Series Volume',
  'Series Published',
  'Series Planned Total',
  'Series Status',
  'Series Checked',
  'Genre',
  'Finished Date',
  'Added At',
  'Word Count',
] as const;
export const HEADERS: Record<string, readonly string[]> = {
  Untitled: MAIN_HEADERS,
  ...{
    'Author Highlights': [
      'Author',
      'Rank',
      'Title',
      'Series',
      'First Published',
      'Cover URL',
      'Source URL',
      'Source',
      'Updated',
    ],
    'Book Quotes': ['Book ID', 'Quote', 'Attribution'],
    'Series Catalog': ['Series', 'Volume', 'Title', 'Author', 'Source URL'],
    'Book Comparisons': [
      'Event ID',
      'Event Type',
      'Client Request ID',
      'Pair Key',
      'Book A ID',
      'Book B ID',
      'Outcome',
      'Compared At',
      'Session ID',
      'Target Event ID',
      'Actor',
      'Algorithm Version',
    ],
    'Book Rankings': [
      'Book ID',
      'Rank',
      'Preference Strength',
      'Standard Error',
      'Effective Decisions',
      'Distinct Opponents',
      'Provisional',
      'Calculated At',
      'Algorithm Version',
      'Data Revision',
    ],
    'Book Recaps': [
      'Book ID',
      'Title',
      'Author',
      'Status',
      'Verified At',
      'Edition',
      'Quick Refresher',
      'Characters and Key Figures',
      'Cheat Sheet',
      'Full Story',
      'Series Handoff',
      'Sources',
      'Paragraph Sources',
      'Reason',
      'Updated At',
    ],
  },
};
export const REQUIRED_HEADERS = ['Book ID', 'Title', 'Author', 'Platform', 'Status'] as const;
